# Rinha de Backend 2026 - Submission
# Victor Hugo dos Santos Farias (@vhtor)

services:
  api1:
    image: vhtor/rinha-backend-2026:latest
    hostname: api1
    environment:
      - RESOURCES_DIR=/app/resources
    deploy:
      resources:
        limits:
          cpus: "0.425"
          memory: "160MB"
    networks:
      - rinha-network
    depends_on:
      - nginx
    healthcheck:
      test: ["CMD", "curl", "f", "http://localhost:9999/ready"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  api2:
    image: vhtor/rinha-backend-2026:latest
    hostname: api2
    environment:
      - RESOURCES_DIR=/app/resources
    deploy:
      resources:
        limits:
          cpus: "0.425"
          memory: "160MB"
    networks:
      - rinha-network
    depends_on:
      - nginx
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:9999/ready || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  nginx:
    image: nginx:alpine
    hostname: nginx
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "30MB"
    networks:
      - rinha-network

networks:
  rinha-network:
    driver: bridge
